### ISSUE TITLE
bug: open js text can not be seen in light mode

### ISSUE THREAD

**Issue by khareyash05** [electron/electronjs.org-new#196]
Open js text in the logo can not be seen in light mode .I would like to work on it
Light mode-
![image](https://user-images.githubusercontent.com/60147732/159110162-79ed052f-5088-4dba-bd62-171f4d0efe81.png)
Dark mode -
![image](https://user-images.githubusercontent.com/60147732/159117624-04333a3d-a822-46c3-9c0d-063f6a664603.png)

**Comment by molant** [comment]
Sure, go for it!
Thanks!

**Comment by srishtiprasadmanit12** [comment]
@molant I see this issue hasn't been worked on ,can you assign me this issue ?

**Comment by molant** [comment]
I've assigned you as well. Who ever makes a PR first wins!

**Comment by Mridul07Sharma** [comment]
@molant This has not been yet resolved, so can you plz assign me this issue?

**Comment by Mridul07Sharma** [comment]
@molant Are these ok?
![4](https://user-images.githubusercontent.com/91523026/160907205-4f1df243-baf4-493a-8a4d-11e2e7e8bd1d.PNG)
![00](https://user-images.githubusercontent.com/91523026/160907524-ad6b8051-c1c2-4374-b67d-780099786301.PNG)

**Comment by molant** [comment]
@Mridul07Sharma I believe you are using the same logo for both themes, right?
I think the right approach would be to use different images, otherwise we will have accessibility issues related to the color contrast.

[The foundation has logos ready to be used here](https://github.com/openjs-foundation/artwork/tree/main/openjs_foundation). I think the ones we should be using are:
- [openjs_foundation-logo-horizontal-color-dark_background.svg](https://github.com/openjs-foundation/artwork/blob/main/openjs_foundation/openjs_foundation-logo-horizontal-color-dark_background.svg)
- [openjs_foundation-logo-horizontal-color.svg](https://github.com/openjs-foundation/artwork/blob/main/openjs_foundation/openjs_foundation-logo-horizontal-color.svg)

Hope this helps!

**Comment by jianrong7** [comment]
hey @molant , I made a PR [here](https://github.com/electron/electronjs.org-new/pull/211)

In dark mode, the logo used would be [this](https://github.com/openjs-foundation/artwork/blob/main/openjs_foundation/openjs_foundation-logo-horizontal-color-dark_background.svg)
Screenshot
![dark-mode](https://user-images.githubusercontent.com/60573059/162600290-f32ae143-f9be-499e-9704-f11688806157.png)


Whereas in light mode, the logo used would be [this](https://github.com/openjs-foundation/artwork/blob/main/openjs_foundation/openjs_foundation-logo-horizontal-color.svg)
![light-mode](https://user-images.githubusercontent.com/60573059/162600293-d0573113-79a0-474d-8236-1516bca78b49.png)
