### ISSUE TITLE
broken image links in new docs

### ISSUE THREAD

**Issue by ckerr** [electron/electronjs.org-new#84]
https://www.electronjs.org/docs/latest/tutorial/performance/#how has broken image links to "../images/performance-heap-prof.png" and "../images/performance-cpu-prof.png"

Some other image links _do_ work, e.g. in https://www.electronjs.org/docs/latest/tutorial/electron-versioning/#version-1x

**Comment by erickzhao** [comment]
An immediate difference I see between the working and non-working images is that the broken ones are written using inline links rather than directly linking the image. It's possible that the MDX parser doesn't know how to handle this syntax.

A quick fix would be to make these direct URL usages upstream.

**Comment by erickzhao** [comment]
The problem seems to also show up on the old website.

We use a markdown AST transformer to fix relative links: https://github.com/electron/i18n/blob/master/lib/transfomers/remark-relative-links.ts

It's possible that the website doesn't know how to handle these because they're using the aforementioned inline link syntax.

**Comment by molant** [comment]
As @erickzhao mentioned, the problem seems to be with inline links. In development the performance one show up to me but not the ones in progress bars.
There are only 2 guides using this format so I'm going to do the change upstream.
